# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(552, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddButton.setFont(font)
        self.AddButton.setObjectName("AddButton")
        self.verticalLayout.addWidget(self.AddButton)
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName("SearchButton")
        self.verticalLayout.addWidget(self.SearchButton)
        self.DelButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DelButton.setFont(font)
        self.DelButton.setObjectName("DelButton")
        self.verticalLayout.addWidget(self.DelButton)
        self.AllButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AllButton.setFont(font)
        self.AllButton.setObjectName("AllButton")
        self.verticalLayout.addWidget(self.AllButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.ListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ListWidget.setObjectName("ListWidget")
        self.ListWidget.setFont(font)
        self.verticalLayout.addWidget(self.ListWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 552, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddButton.setText(_translate("MainWindow", "Добавить видео"))
        self.SearchButton.setText(_translate("MainWindow", "Найти Видео"))
        self.DelButton.setText(_translate("MainWindow", "Удалить видео"))
        self.AllButton.setText(_translate("MainWindow", "Показать все"))
